MCU = atmega32u4

BOOTLOADER = caterina

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
STENO_ENABLE = yes
SPLIT_KEYBOARD = no
LTO_ENABLE = yes
NO_TAPPING = yes
NO_PRINT = yes
VIRTSER_ENABLE = yes
MIDI_ENABLE = no
