MCU = atmega32u4

BOOTLOADER = caterina

STENO_ENABLE = yes
LTO_ENABLE = yes
NO_TAPPING = yes
NO_PRINT = yes
NKRO_ENABLE = yes

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
SPLIT_KEYBOARD = no
VIRTSER_ENABLE = no
MIDI_ENABLE = no
